name: CI

on: [push]

jobs:
  test:
    name: 'Test'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install and test
      run: |
        npm ci
        npm test
      env:
        CI: true
